name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'

categories:
  - title: '🚨 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
      - 'fix'
      - 'patch'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
      - 'avm-update'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'

exclude-labels:
  - 'skip-release'
  - 'skip-changelog'

autolabeler:
  - label: 'documentation'
    branch:
      - '/docs?\/.+/'
    files:
      - '*.md'
      - 'docs/**/*'
      - 'documentation/**/*'
  - label: 'bugfix'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feat(ure)?\/.+/'
  - label: 'breaking-change'
    branch:
      - '/breaking\/.+/'
  - label: 'dependencies'
    files:
      - 'renovate.json'
      - '.github/dependabot.yml'
  - label: 'test'
    files:
      - 'tests/**/*'

version-resolver:
  major:
    labels:
      - 'breaking-change'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  patch:
    labels:
      - 'bugfix'
      - 'fix'
      - 'patch'
      - 'dependencies'
      - 'avm-update'
  default: patch

template: |
  ## What's Changed
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  
  ## Usage
  
  Reference this version in your pipeline:
  
  ```yaml
  resources:
    repositories:
      - repository: templates
        type: github
        name: $OWNER/$REPOSITORY
        ref: v$RESOLVED_VERSION
  ```

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

replacers:

  - search: '/^(feat|fix|docs|chore|refactor|test|ci)(\(.+\))?: /i'
    replace: ''

no-contributors-template: |
  This release was automatically generated.
