name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'

categories:
  - title: '🚨 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
      - 'fix'
      - 'patch'
  - title: '📦 AVM Dependencies'
    labels:
      - 'avm-dependency-update'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'

exclude-labels:
  - 'skip-release'
  - 'skip-changelog'

autolabeler:
  - label: 'documentation'
    branch:
      - '/docs?\/.+/'
    files:
      - '*.md'
      - 'docs/**/*'
      - 'documentation/**/*'
  - label: 'enhancement'
    branch:
      - '/feat(ure)?\/.+/'
    files:
      - 'modules/**/*.tf'
      - 'main.tf'
      - 'variables.tf'
      - 'outputs.tf'
      - 'locals.tf'
      - 'data.tf'
      - 'provider.tf'
    exclude:
      - '*.md'
      - 'docs/**/*'
      - 'documentation/**/*'  
  - label: 'bugfix'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
  - label: 'breaking-change'
    branch:
      - '/breaking\/.+/'
  - label: 'test'
    files:
      - 'tests/**/*'

version-resolver:
  major:
    labels:
      - 'breaking-change'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  patch:
    labels:
      - 'bugfix'
      - 'fix'
      - 'patch'
      - 'avm-dependency-update'
  default: patch

template: |
  ## What's Changed
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  
  ## Usage
  
  Reference this module in your Terraform code:
  
  ```hcl
  module "example" {
    source = "git::https://github.com/$OWNER/$REPOSITORY?ref=v$RESOLVED_VERSION"
  }
  ```

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

replacers:
  - search: '/^(feat|fix|docs|chore|refactor|test|ci)(\(.+\))?: /i'
    replace: ''

no-contributors-template: |
  This release was automatically generated.
